export const NoteBookFormValues = {
  id: null,
  title: "",
  type: null,
  typeName: "",
  objective: "",
  protocol: "",
  principalInvestigator: "",
  fundingSource: "",
  budget: null,
  projectTimeline: "",
  content: "",
  workflowType: "",
  technicianId: null,
  participantIds: [],
  systemUserId: null,
  status: "",
  sampleIds: [],
  tags: [],
  analyzerIds: [],
  inventoryInstrumentIds: [],
  isTemplate: null,
  templateId: null,
  pages: [
    {
      title: "",
      content: "",
      instructions: "",
      tests: [],
    },
  ],
  files: [
    {
      base64File: "",
      fileType: "",
    },
  ],
  comments: [],
};

export const NoteBookInitialData = {
  id: null,
  title: "",
  type: null,
  typeName: "",
  dateCreated: "",
  status: "DRAFT",
  tags: [],
  objective: "",
  protocol: "",
  principalInvestigator: "",
  fundingSource: "",
  budget: null,
  projectTimeline: "",
  content: "",
  workflowType: "",
  technicianId: null,
  participantIds: [],
  systemUserId: null,
  technicianName: "",
  samples: [],
  analyzers: [],
  pages: [],
  files: [],
  comments: [],
  isTemplate: null,
  questionnaireFhirUuid: null,
};

// export const NoteBookInitialData = {
//   id: null,
//   title: "",
//   type: null,
//   lastName: "",
//   firstName: "",
//   gender: "",
//   dateCreated: "",
//   tags: [],
//   project: "",
//   objective: "",
//   protocol: "",
//   content: "",
//   technicianId: null,
//   patientId: null,
//   systemUserId: null,
//   technicianName: "",
//   samples: [
//     {
//       id: null,
//       sampleType: "",
//       collectionDate: "",
//       patientId
//       results: [
//         {
//           test: "",
//           result: "",
//           dateCreated: "",
//         },
//       ],
//     },
//   ],
//   analyserIds: [],
//   pages: [
//     {
//       title: "",
//       content: "",
//       instructions: "",
//     },
//   ],
//   files: [
//     {
//       fileData: "",
//       fileType: "",
//     },
//   ],
// };
