import React, { useState, useCallback, useEffect } from "react";
import {
  Modal,
  FileUploaderDropContainer,
  FileUploaderItem,
  Select,
  SelectItem,
  Button,
  InlineNotification,
  Tag,
  Loading,
  StructuredListWrapper,
  StructuredListHead,
  StructuredListRow,
  StructuredListCell,
  StructuredListBody,
  Accordion,
  AccordionItem,
  Grid,
  Column,
  DataTable,
  Table,
  TableHead,
  TableRow,
  TableHeader,
  TableBody,
  TableCell,
  TextArea,
} from "@carbon/react";
import {
  Upload,
  Checkmark,
  Warning,
  Information,
  Download,
} from "@carbon/react/icons";
import { FormattedMessage, useIntl } from "react-intl";
import config from "../../../config.json";
import "./NotebookWorkflow.css";

/**
 * Expected dataPoints for MNTD Sample Import Manifest.
 * Aligned with MNTD Laboratory workflow requirements.
 * Note: sampleType.validValues is now fetched dynamically from the backend API
 */
const EXPECTED_DATA_POINTS = {
  required: [
    {
      key: "projectName",
      label: "Project Name",
      description: "Name of the research project or study",
      example: "Malaria Genomic Surveillance 2024",
    },
    {
      key: "sampleIdTag",
      label: "Sample ID/Tag",
      description:
        "Pre-labeled sample identifier (free text: letters, numbers, symbols)",
      example: "Ach 21-FY004",
    },
    {
      key: "numberOfSamples",
      label: "Number of Samples",
      description: "Quantity and container type",
      example: "2 boxes, 1 bag, 10 tubes",
    },
    {
      key: "sampleSourceLocation",
      label: "Sample Source Location",
      description: "Geographic origin or collection site of the sample",
      example: "Jimma Zone, Oromia Region",
    },
    {
      key: "broughtBy",
      label: "Brought By",
      description: "Person or institution delivering the sample",
      example: "Dr. Abebe, UoG Research Team",
    },
    {
      key: "receivedDateTime",
      label: "Received Date & Time",
      description: "When the sample was received at the laboratory",
      example: "2024-06-15 09:30",
    },
    {
      key: "receptionistName",
      label: "Receptionist Name",
      description: "Name of the person who received the sample",
      example: "Tigist Hailu",
    },
  ],
  sampleType: {
    key: "sampleType",
    label: "Sample Type",
    description: "Type of MNTD sample (validated against MNTD lab types)",
    example:
      "Whole Blood, Dried Blood Spots, Colony mosquito, Wild mosquito, etc.",
  },
  optional: [
    {
      key: "feedingStatus",
      label: "Feeding Status",
      description: "For vector samples - feeding state",
      example: "Fed, Unfed, Blood-fed",
    },
    {
      key: "parasiteStage",
      label: "Parasite Stage",
      description: "Developmental stage of parasite samples",
      example: "30-40 pf, Ring stage, Gametocyte",
    },
    {
      key: "storageCondition",
      label: "Storage Condition",
      description: "Required storage temperature/conditions",
      example: "-80C, -20C, 4C, Room Temperature",
    },
    {
      key: "externalOrganization",
      label: "External Organization",
      description: "Source organization for external samples",
      example: "UOG, WHO, FMOH",
    },
    {
      key: "countryOfOrigin",
      label: "Country of Origin",
      description: "For international samples",
      example: "Ethiopia, Kenya, Uganda",
    },
    {
      key: "collectionMethod",
      label: "Collection Method",
      description: "How the sample was collected",
      example: "Light trap, PSC, HLC, Venipuncture",
    },
    {
      key: "specimenCondition",
      label: "Specimen Condition",
      description: "Condition of the sample on arrival",
      example: "Good, Hemolyzed, Lipemic, Damaged",
    },
    {
      key: "remarks",
      label: "Remarks",
      description: "Additional notes or observations",
      example: "Priority sample for WHO study",
    },
  ],
  autoGenerated: [
    {
      key: "accessionNumber",
      label: "Accession Number",
      description: "System-generated unique laboratory identifier",
    },
    {
      key: "barcodeQrCode",
      label: "Barcode/QR Code",
      description: "System-generated scannable identifier",
    },
  ],
};

/**
 * MNTDManifestImportModal - CSV import modal for MNTD workflow.
 * Supports mapping MNTD-specific columns aligned with the dataPoints schema.
 */
function MNTDManifestImportModal({ open, onClose, entryId, onImportSuccess }) {
  const intl = useIntl();

  const [file, setFile] = useState(null);
  const [fileError, setFileError] = useState(null);
  const [csvHeaders, setCsvHeaders] = useState([]);
  const [columnMapping, setColumnMapping] = useState({
    // Required fields
    projectNameColumn: "",
    sampleIdTagColumn: "",
    numberOfSamplesColumn: "",
    sampleSourceLocationColumn: "",
    broughtByColumn: "",
    receivedDateTimeColumn: "",
    receptionistNameColumn: "",
    // Sample type (validated against MNTD lab types)
    sampleTypeColumn: "",
    // Optional fields
    feedingStatusColumn: "",
    parasiteStageColumn: "",
    storageConditionColumn: "",
    externalOrganizationColumn: "",
    countryOfOriginColumn: "",
    collectionMethodColumn: "",
    specimenConditionColumn: "",
    remarksColumn: "",
  });

  const [step, setStep] = useState(1);
  const [manifestDescription, setManifestDescription] = useState("");
  const [previewData, setPreviewData] = useState(null);
  const [previewErrors, setPreviewErrors] = useState([]);
  const [isPreviewLoading, setIsPreviewLoading] = useState(false);
  const [isImporting, setIsImporting] = useState(false);

  // Dynamic sample types from backend
  const [validSampleTypes, setValidSampleTypes] = useState([]);
  const [isSampleTypesLoading, setIsSampleTypesLoading] = useState(false);

  // Fetch valid sample types from backend when modal opens
  useEffect(() => {
    if (open) {
      setIsSampleTypesLoading(true);
      fetch(`${config.serverBaseUrl}/rest/notebook/mntd/sample-types`, {
        method: "GET",
        credentials: "include",
        headers: {
          "X-CSRF-Token": localStorage.getItem("CSRF"),
        },
      })
        .then((response) => response.json())
        .then((data) => {
          if (data.sampleTypes) {
            setValidSampleTypes(data.sampleTypes.map((st) => st.description));
          }
        })
        .catch((error) => {
          console.error("Failed to fetch sample types:", error);
          // Fallback to empty array - validation will still happen on backend
          setValidSampleTypes([]);
        })
        .finally(() => {
          setIsSampleTypesLoading(false);
        });
    }
  }, [open]);

  /**
   * Auto-detect and map CSV columns based on header names.
   * Matches against expected column keys (case-insensitive).
   */
  const autoMapColumns = useCallback((headers) => {
    // Map of expected column keys to their form field names
    const columnKeyToField = {
      projectname: "projectNameColumn",
      project: "projectNameColumn",
      sampleid: "sampleIdTagColumn",
      sampletag: "sampleIdTagColumn",
      sampleidtag: "sampleIdTagColumn",
      "sample id": "sampleIdTagColumn",
      numberofsamples: "numberOfSamplesColumn",
      numsamples: "numberOfSamplesColumn",
      quantity: "numberOfSamplesColumn",
      samplesourcelocation: "sampleSourceLocationColumn",
      sourcelocation: "sampleSourceLocationColumn",
      location: "sampleSourceLocationColumn",
      origin: "sampleSourceLocationColumn",
      broughtby: "broughtByColumn",
      deliveredby: "broughtByColumn",
      submittedby: "broughtByColumn",
      receiveddatetime: "receivedDateTimeColumn",
      receiveddate: "receivedDateTimeColumn",
      datereceived: "receivedDateTimeColumn",
      receptiondate: "receivedDateTimeColumn",
      receptionistname: "receptionistNameColumn",
      receptionist: "receptionistNameColumn",
      receivedby: "receptionistNameColumn",
      sampletype: "sampleTypeColumn",
      type: "sampleTypeColumn",
      specimenType: "sampleTypeColumn",
      feedingstatus: "feedingStatusColumn",
      feeding: "feedingStatusColumn",
      parasitestage: "parasiteStageColumn",
      stage: "parasiteStageColumn",
      storagecondition: "storageConditionColumn",
      storage: "storageConditionColumn",
      externalorganization: "externalOrganizationColumn",
      organization: "externalOrganizationColumn",
      countryoforigin: "countryOfOriginColumn",
      country: "countryOfOriginColumn",
      collectionmethod: "collectionMethodColumn",
      method: "collectionMethodColumn",
      specimencondition: "specimenConditionColumn",
      condition: "specimenConditionColumn",
      remarks: "remarksColumn",
      notes: "remarksColumn",
      comments: "remarksColumn",
    };

    const newMapping = {};

    headers.forEach((header, index) => {
      // Normalize header: lowercase, remove spaces/underscores/hyphens/slashes
      const normalizedHeader = header
        .toLowerCase()
        .replace(/[\s_\-/]/g, "")
        .trim();

      // Check if this normalized header matches any expected column key
      const fieldName = columnKeyToField[normalizedHeader];
      if (fieldName) {
        newMapping[fieldName] = header;
      }
    });

    // Update the column mapping with auto-detected values
    setColumnMapping((prev) => ({
      ...prev,
      ...newMapping,
    }));
  }, []);

  // Handle file upload
  const handleFileAdded = useCallback(
    (event, { addedFiles }) => {
      const addedFile = addedFiles[0];
      if (!addedFile) return;

      if (!addedFile.name.endsWith(".csv")) {
        setFileError(
          intl.formatMessage({
            id: "notebook.mntd.manifest.error.invalidFileType",
            defaultMessage: "Please upload a CSV file",
          }),
        );
        return;
      }

      setFile(addedFile);
      setFileError(null);

      // Read file to extract headers
      const reader = new FileReader();
      reader.onload = (e) => {
        const text = e.target.result;
        const firstLine = text.split("\n")[0];
        const headers = firstLine
          .split(",")
          .map((h) => h.trim().replace(/"/g, ""));
        setCsvHeaders(headers);
        // Auto-map columns based on header names
        autoMapColumns(headers);
        setStep(2);
      };
      reader.readAsText(addedFile);
    },
    [intl, autoMapColumns],
  );

  // Handle file removal
  const handleRemoveFile = useCallback(() => {
    setFile(null);
    setCsvHeaders([]);
    setColumnMapping({
      projectNameColumn: "",
      sampleIdTagColumn: "",
      numberOfSamplesColumn: "",
      sampleSourceLocationColumn: "",
      broughtByColumn: "",
      receivedDateTimeColumn: "",
      receptionistNameColumn: "",
      sampleTypeColumn: "",
      feedingStatusColumn: "",
      parasiteStageColumn: "",
      storageConditionColumn: "",
      externalOrganizationColumn: "",
      countryOfOriginColumn: "",
      collectionMethodColumn: "",
      specimenConditionColumn: "",
      remarksColumn: "",
    });
    setManifestDescription("");
    setPreviewData(null);
    setPreviewErrors([]);
    setStep(1);
  }, []);

  // Handle column mapping change
  const handleMappingChange = useCallback((field, value) => {
    setColumnMapping((prev) => ({
      ...prev,
      [field]: value,
    }));
  }, []);

  // Check if required fields are mapped
  const isRequiredMappingComplete = useCallback(() => {
    return (
      columnMapping.projectNameColumn &&
      columnMapping.sampleIdTagColumn &&
      columnMapping.sampleTypeColumn &&
      columnMapping.sampleSourceLocationColumn &&
      columnMapping.broughtByColumn &&
      columnMapping.receivedDateTimeColumn &&
      columnMapping.receptionistNameColumn
    );
  }, [columnMapping]);

  // Build multipart form data for preview/import requests
  const buildFormData = useCallback(() => {
    const formData = new FormData();
    formData.append("file", file);
    formData.append(
      "mapping",
      new Blob([JSON.stringify(columnMapping)], { type: "application/json" }),
    );
    formData.append("manifestDescription", manifestDescription);
    return formData;
  }, [file, columnMapping, manifestDescription]);

  // Preview import
  const handlePreview = useCallback(async () => {
    if (!file) {
      setPreviewErrors([
        {
          rowNumber: 0,
          column: "file",
          message: "Please upload a CSV file before previewing.",
        },
      ]);
      return;
    }
    if (!entryId) {
      setPreviewErrors([
        {
          rowNumber: 0,
          column: "entry",
          message: "Notebook entry is not ready. Please refresh and try again.",
        },
      ]);
      return;
    }

    setIsPreviewLoading(true);
    setPreviewErrors([]);

    try {
      const response = await fetch(
        `${config.serverBaseUrl}/rest/notebook/mntd/entry/${entryId}/samples/preview-manifest`,
        {
          method: "POST",
          credentials: "include",
          headers: {
            "X-CSRF-Token": localStorage.getItem("CSRF"),
          },
          body: buildFormData(),
        },
      );

      const data = await response.json();
      if (response.ok) {
        setPreviewData(data);
        setPreviewErrors(data.errors || []);
        setStep(3);
      } else {
        setPreviewErrors(
          data.errors || [
            {
              rowNumber: 0,
              column: "file",
              message:
                data.message ||
                data.error ||
                `Preview failed (${response.status})`,
            },
          ],
        );
      }
    } catch (error) {
      setPreviewErrors([
        { rowNumber: 0, column: "file", message: error.message },
      ]);
    } finally {
      setIsPreviewLoading(false);
    }
  }, [file, entryId, buildFormData]);

  // Execute import
  const handleImport = useCallback(async () => {
    if (!file || !entryId) return;

    setIsImporting(true);
    setPreviewErrors([]);

    try {
      const response = await fetch(
        `${config.serverBaseUrl}/rest/notebook/mntd/entry/${entryId}/samples/create-from-manifest`,
        {
          method: "POST",
          credentials: "include",
          headers: {
            "X-CSRF-Token": localStorage.getItem("CSRF"),
          },
          body: buildFormData(),
        },
      );

      const data = await response.json();
      if (response.ok && data.success) {
        setStep(4);
        if (onImportSuccess) {
          onImportSuccess(data);
        }
      } else {
        setPreviewErrors(
          data.errors || [
            {
              rowNumber: 0,
              column: "import",
              message:
                data.message ||
                data.error ||
                `Import failed (${response.status})`,
            },
          ],
        );
      }
    } catch (error) {
      setPreviewErrors([
        { rowNumber: 0, column: "import", message: error.message },
      ]);
    } finally {
      setIsImporting(false);
    }
  }, [file, entryId, buildFormData, onImportSuccess]);

  // Close modal and reset
  const handleClose = useCallback(() => {
    handleRemoveFile();
    if (onClose) {
      onClose();
    }
  }, [handleRemoveFile, onClose]);

  // Download CSV template
  const handleDownloadTemplate = useCallback(() => {
    window.open(
      `${config.serverBaseUrl}/rest/notebook/mntd/manifest-template`,
      "_blank",
    );
  }, []);

  // Get primary button text based on step
  const getPrimaryButtonText = () => {
    switch (step) {
      case 1:
        return intl.formatMessage({
          id: "label.button.next",
          defaultMessage: "Next",
        });
      case 2:
        return intl.formatMessage({
          id: "label.button.preview",
          defaultMessage: "Preview",
        });
      case 3:
        return intl.formatMessage({
          id: "label.button.import",
          defaultMessage: "Import",
        });
      case 4:
        return intl.formatMessage({
          id: "label.button.done",
          defaultMessage: "Done",
        });
      default:
        return intl.formatMessage({
          id: "label.button.next",
          defaultMessage: "Next",
        });
    }
  };

  // Handle primary button click
  const handlePrimaryClick = () => {
    switch (step) {
      case 2:
        handlePreview();
        break;
      case 3:
        handleImport();
        break;
      case 4:
        handleClose();
        break;
      default:
        break;
    }
  };

  // Check if primary button should be disabled
  const isPrimaryDisabled = () => {
    switch (step) {
      case 1:
        return !file;
      case 2:
        return !isRequiredMappingComplete() || isPreviewLoading;
      case 3:
        return previewErrors.length > 0 || isImporting;
      default:
        return false;
    }
  };

  return (
    <Modal
      open={open}
      onRequestClose={handleClose}
      modalHeading={intl.formatMessage({
        id: "notebook.mntd.manifest.title",
        defaultMessage: "Import MNTD Samples from Manifest",
      })}
      primaryButtonText={getPrimaryButtonText()}
      secondaryButtonText={intl.formatMessage({
        id: "label.button.cancel",
        defaultMessage: "Cancel",
      })}
      onRequestSubmit={handlePrimaryClick}
      onSecondarySubmit={handleClose}
      size="lg"
      primaryButtonDisabled={isPrimaryDisabled()}
      className="manifest-import-modal"
    >
      <div className="mntd-manifest-import-modal">
        {/* Step 1: Instructions & File Upload */}
        {step === 1 && (
          <div className="import-step">
            <div className="step-header">
              <h5>
                <FormattedMessage
                  id="notebook.mntd.manifest.step1.title"
                  defaultMessage="Step 1: Upload Manifest CSV"
                />
              </h5>
              <p className="step-description">
                <FormattedMessage
                  id="notebook.mntd.manifest.step1.description"
                  defaultMessage="Upload a CSV file containing sample data. The system will auto-detect column mappings based on header names."
                />
              </p>
            </div>

            {/* Download Template Button */}
            <div className="template-download-section">
              <Button
                kind="tertiary"
                size="sm"
                renderIcon={Download}
                onClick={handleDownloadTemplate}
              >
                <FormattedMessage
                  id="notebook.mntd.manifest.downloadTemplate"
                  defaultMessage="Download CSV Template"
                />
              </Button>
            </div>

            {/* Expected Data Points Documentation */}
            <Accordion>
              <AccordionItem
                title={intl.formatMessage({
                  id: "notebook.mntd.manifest.dataPointsTitle",
                  defaultMessage: "Expected Data Points (Click to expand)",
                })}
              >
                <div className="data-points-section">
                  {/* Required Fields */}
                  <div className="data-points-group">
                    <h6>
                      <FormattedMessage
                        id="notebook.mntd.manifest.requiredFields"
                        defaultMessage="Required Fields"
                      />
                    </h6>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.example"
                              defaultMessage="Example"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.required.map((field) => (
                          <StructuredListRow key={field.key}>
                            <StructuredListCell>
                              <code className="column-key">{field.key}</code>
                            </StructuredListCell>
                            <StructuredListCell>
                              {field.description}
                            </StructuredListCell>
                            <StructuredListCell>
                              <em>{field.example}</em>
                            </StructuredListCell>
                          </StructuredListRow>
                        ))}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>

                  {/* Sample Type Field */}
                  <div className="data-points-group">
                    <h6>
                      <FormattedMessage
                        id="notebook.mntd.manifest.sampleTypeField"
                        defaultMessage="Sample Type (Required)"
                      />
                    </h6>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.validValues"
                              defaultMessage="Valid Values"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        <StructuredListRow>
                          <StructuredListCell>
                            <code className="column-key">
                              {EXPECTED_DATA_POINTS.sampleType.key}
                            </code>
                          </StructuredListCell>
                          <StructuredListCell>
                            {EXPECTED_DATA_POINTS.sampleType.description}
                          </StructuredListCell>
                          <StructuredListCell>
                            <div className="valid-values-list">
                              {isSampleTypesLoading ? (
                                <Loading
                                  small
                                  withOverlay={false}
                                  description="Loading sample types..."
                                />
                              ) : validSampleTypes.length > 0 ? (
                                validSampleTypes.map((value, idx) => (
                                  <Tag key={idx} type="outline" size="sm">
                                    {value}
                                  </Tag>
                                ))
                              ) : (
                                <span className="no-sample-types">
                                  <FormattedMessage
                                    id="notebook.mntd.manifest.noSampleTypes"
                                    defaultMessage="No sample types configured. Contact administrator."
                                  />
                                </span>
                              )}
                            </div>
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>

                  {/* Optional Fields */}
                  <div className="data-points-group">
                    <h6>
                      <FormattedMessage
                        id="notebook.mntd.manifest.optionalFields"
                        defaultMessage="Optional Fields"
                      />
                    </h6>
                    <StructuredListWrapper isCondensed>
                      <StructuredListHead>
                        <StructuredListRow head>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.column"
                              defaultMessage="Column"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.description"
                              defaultMessage="Description"
                            />
                          </StructuredListCell>
                          <StructuredListCell head>
                            <FormattedMessage
                              id="label.example"
                              defaultMessage="Example"
                            />
                          </StructuredListCell>
                        </StructuredListRow>
                      </StructuredListHead>
                      <StructuredListBody>
                        {EXPECTED_DATA_POINTS.optional.map((field) => (
                          <StructuredListRow key={field.key}>
                            <StructuredListCell>
                              <code className="column-key">{field.key}</code>
                            </StructuredListCell>
                            <StructuredListCell>
                              {field.description}
                            </StructuredListCell>
                            <StructuredListCell>
                              <em>{field.example}</em>
                            </StructuredListCell>
                          </StructuredListRow>
                        ))}
                      </StructuredListBody>
                    </StructuredListWrapper>
                  </div>
                </div>
              </AccordionItem>
            </Accordion>

            {/* File Upload */}
            <div className="file-upload-section">
              <FileUploaderDropContainer
                accept={[".csv"]}
                labelText={intl.formatMessage({
                  id: "notebook.mntd.manifest.dropzone",
                  defaultMessage:
                    "Drag and drop a CSV file here or click to upload",
                })}
                onAddFiles={handleFileAdded}
              />
              {fileError && (
                <InlineNotification
                  kind="error"
                  title={fileError}
                  lowContrast
                  hideCloseButton
                />
              )}
            </div>
          </div>
        )}

        {/* Step 2: Column Mapping */}
        {step === 2 && (
          <div className="import-step">
            <div className="step-header">
              <h5>
                <FormattedMessage
                  id="notebook.mntd.manifest.step2.title"
                  defaultMessage="Step 2: Map Columns"
                />
              </h5>
              <p className="step-description">
                <FormattedMessage
                  id="notebook.mntd.manifest.step2.description"
                  defaultMessage="Map the CSV columns to the required fields. Columns have been auto-detected where possible."
                />
              </p>
            </div>

            {file && (
              <FileUploaderItem
                name={file.name}
                status="edit"
                onDelete={handleRemoveFile}
              />
            )}

            {/* Manifest Description */}
            <div className="manifest-description-section">
              <TextArea
                id="manifestDescription"
                labelText={intl.formatMessage({
                  id: "notebook.mntd.manifest.description",
                  defaultMessage: "Manifest Description / Notes",
                })}
                placeholder={intl.formatMessage({
                  id: "notebook.mntd.manifest.description.placeholder",
                  defaultMessage:
                    "Enter any additional information about this manifest import...",
                })}
                value={manifestDescription}
                onChange={(e) => setManifestDescription(e.target.value)}
                rows={3}
                maxCount={500}
              />
            </div>

            {/* Required Fields Mapping */}
            <div className="mapping-section">
              <h6 className="mapping-section-title">
                <Tag type="red" size="sm">
                  <FormattedMessage
                    id="label.required"
                    defaultMessage="Required"
                  />
                </Tag>
                <FormattedMessage
                  id="notebook.mntd.manifest.requiredFields"
                  defaultMessage="Required Fields"
                />
              </h6>
              <Grid fullWidth>
                <Column lg={8} md={4} sm={4}>
                  <Select
                    id="projectNameColumn"
                    labelText={intl.formatMessage({
                      id: "notebook.mntd.field.projectName",
                      defaultMessage: "Project Name *",
                    })}
                    value={columnMapping.projectNameColumn}
                    onChange={(e) =>
                      handleMappingChange("projectNameColumn", e.target.value)
                    }
                  >
                    <SelectItem value="" text="Select column..." />
                    {csvHeaders.map((header) => (
                      <SelectItem key={header} value={header} text={header} />
                    ))}
                  </Select>
                </Column>
                <Column lg={8} md={4} sm={4}>
                  <Select
                    id="sampleTypeColumn"
                    labelText={intl.formatMessage({
                      id: "notebook.mntd.field.sampleType",
                      defaultMessage: "Sample Type *",
                    })}
                    value={columnMapping.sampleTypeColumn}
                    onChange={(e) =>
                      handleMappingChange("sampleTypeColumn", e.target.value)
                    }
                  >
                    <SelectItem value="" text="Select column..." />
                    {csvHeaders.map((header) => (
                      <SelectItem key={header} value={header} text={header} />
                    ))}
                  </Select>
                </Column>
                <Column lg={8} md={4} sm={4}>
                  <Select
                    id="sampleIdTagColumn"
                    labelText={intl.formatMessage({
                      id: "notebook.mntd.field.sampleIdTag",
                      defaultMessage: "Sample ID/Tag *",
                    })}
                    value={columnMapping.sampleIdTagColumn}
                    onChange={(e) =>
                      handleMappingChange("sampleIdTagColumn", e.target.value)
                    }
                  >
                    <SelectItem value="" text="Select column..." />
                    {csvHeaders.map((header) => (
                      <SelectItem key={header} value={header} text={header} />
                    ))}
                  </Select>
                </Column>
                <Column lg={8} md={4} sm={4}>
                  <Select
                    id="numberOfSamplesColumn"
                    labelText={intl.formatMessage({
                      id: "notebook.mntd.field.numberOfSamples",
                      defaultMessage: "Number of Samples *",
                    })}
                    value={columnMapping.numberOfSamplesColumn}
                    onChange={(e) =>
                      handleMappingChange(
                        "numberOfSamplesColumn",
                        e.target.value,
                      )
                    }
                  >
                    <SelectItem value="" text="Select column..." />
                    {csvHeaders.map((header) => (
                      <SelectItem key={header} value={header} text={header} />
                    ))}
                  </Select>
                </Column>
                <Column lg={8} md={4} sm={4}>
                  <Select
                    id="sampleSourceLocationColumn"
                    labelText={intl.formatMessage({
                      id: "notebook.mntd.field.sampleSourceLocation",
                      defaultMessage: "Sample Source Location *",
                    })}
                    value={columnMapping.sampleSourceLocationColumn}
                    onChange={(e) =>
                      handleMappingChange(
                        "sampleSourceLocationColumn",
                        e.target.value,
                      )
                    }
                  >
                    <SelectItem value="" text="Select column..." />
                    {csvHeaders.map((header) => (
                      <SelectItem key={header} value={header} text={header} />
                    ))}
                  </Select>
                </Column>
                <Column lg={8} md={4} sm={4}>
                  <Select
                    id="broughtByColumn"
                    labelText={intl.formatMessage({
                      id: "notebook.mntd.field.broughtBy",
                      defaultMessage: "Brought By *",
                    })}
                    value={columnMapping.broughtByColumn}
                    onChange={(e) =>
                      handleMappingChange("broughtByColumn", e.target.value)
                    }
                  >
                    <SelectItem value="" text="Select column..." />
                    {csvHeaders.map((header) => (
                      <SelectItem key={header} value={header} text={header} />
                    ))}
                  </Select>
                </Column>
                <Column lg={8} md={4} sm={4}>
                  <Select
                    id="receivedDateTimeColumn"
                    labelText={intl.formatMessage({
                      id: "notebook.mntd.field.receivedDateTime",
                      defaultMessage: "Received Date & Time *",
                    })}
                    value={columnMapping.receivedDateTimeColumn}
                    onChange={(e) =>
                      handleMappingChange(
                        "receivedDateTimeColumn",
                        e.target.value,
                      )
                    }
                  >
                    <SelectItem value="" text="Select column..." />
                    {csvHeaders.map((header) => (
                      <SelectItem key={header} value={header} text={header} />
                    ))}
                  </Select>
                </Column>
                <Column lg={8} md={4} sm={4}>
                  <Select
                    id="receptionistNameColumn"
                    labelText={intl.formatMessage({
                      id: "notebook.mntd.field.receptionistName",
                      defaultMessage: "Receptionist Name *",
                    })}
                    value={columnMapping.receptionistNameColumn}
                    onChange={(e) =>
                      handleMappingChange(
                        "receptionistNameColumn",
                        e.target.value,
                      )
                    }
                  >
                    <SelectItem value="" text="Select column..." />
                    {csvHeaders.map((header) => (
                      <SelectItem key={header} value={header} text={header} />
                    ))}
                  </Select>
                </Column>
              </Grid>
            </div>

            {/* Optional Fields Mapping */}
            <Accordion>
              <AccordionItem
                title={intl.formatMessage({
                  id: "notebook.mntd.manifest.optionalFieldsMapping",
                  defaultMessage: "Optional Fields (Click to expand)",
                })}
              >
                <Grid fullWidth>
                  <Column lg={8} md={4} sm={4}>
                    <Select
                      id="feedingStatusColumn"
                      labelText={intl.formatMessage({
                        id: "notebook.mntd.field.feedingStatus",
                        defaultMessage: "Feeding Status",
                      })}
                      value={columnMapping.feedingStatusColumn}
                      onChange={(e) =>
                        handleMappingChange(
                          "feedingStatusColumn",
                          e.target.value,
                        )
                      }
                    >
                      <SelectItem value="" text="Select column..." />
                      {csvHeaders.map((header) => (
                        <SelectItem key={header} value={header} text={header} />
                      ))}
                    </Select>
                  </Column>
                  <Column lg={8} md={4} sm={4}>
                    <Select
                      id="parasiteStageColumn"
                      labelText={intl.formatMessage({
                        id: "notebook.mntd.field.parasiteStage",
                        defaultMessage: "Parasite Stage",
                      })}
                      value={columnMapping.parasiteStageColumn}
                      onChange={(e) =>
                        handleMappingChange(
                          "parasiteStageColumn",
                          e.target.value,
                        )
                      }
                    >
                      <SelectItem value="" text="Select column..." />
                      {csvHeaders.map((header) => (
                        <SelectItem key={header} value={header} text={header} />
                      ))}
                    </Select>
                  </Column>
                  <Column lg={8} md={4} sm={4}>
                    <Select
                      id="storageConditionColumn"
                      labelText={intl.formatMessage({
                        id: "notebook.mntd.field.storageCondition",
                        defaultMessage: "Storage Condition",
                      })}
                      value={columnMapping.storageConditionColumn}
                      onChange={(e) =>
                        handleMappingChange(
                          "storageConditionColumn",
                          e.target.value,
                        )
                      }
                    >
                      <SelectItem value="" text="Select column..." />
                      {csvHeaders.map((header) => (
                        <SelectItem key={header} value={header} text={header} />
                      ))}
                    </Select>
                  </Column>
                  <Column lg={8} md={4} sm={4}>
                    <Select
                      id="externalOrganizationColumn"
                      labelText={intl.formatMessage({
                        id: "notebook.mntd.field.externalOrganization",
                        defaultMessage: "External Organization",
                      })}
                      value={columnMapping.externalOrganizationColumn}
                      onChange={(e) =>
                        handleMappingChange(
                          "externalOrganizationColumn",
                          e.target.value,
                        )
                      }
                    >
                      <SelectItem value="" text="Select column..." />
                      {csvHeaders.map((header) => (
                        <SelectItem key={header} value={header} text={header} />
                      ))}
                    </Select>
                  </Column>
                  <Column lg={8} md={4} sm={4}>
                    <Select
                      id="countryOfOriginColumn"
                      labelText={intl.formatMessage({
                        id: "notebook.mntd.field.countryOfOrigin",
                        defaultMessage: "Country of Origin",
                      })}
                      value={columnMapping.countryOfOriginColumn}
                      onChange={(e) =>
                        handleMappingChange(
                          "countryOfOriginColumn",
                          e.target.value,
                        )
                      }
                    >
                      <SelectItem value="" text="Select column..." />
                      {csvHeaders.map((header) => (
                        <SelectItem key={header} value={header} text={header} />
                      ))}
                    </Select>
                  </Column>
                  <Column lg={8} md={4} sm={4}>
                    <Select
                      id="collectionMethodColumn"
                      labelText={intl.formatMessage({
                        id: "notebook.mntd.field.collectionMethod",
                        defaultMessage: "Collection Method",
                      })}
                      value={columnMapping.collectionMethodColumn}
                      onChange={(e) =>
                        handleMappingChange(
                          "collectionMethodColumn",
                          e.target.value,
                        )
                      }
                    >
                      <SelectItem value="" text="Select column..." />
                      {csvHeaders.map((header) => (
                        <SelectItem key={header} value={header} text={header} />
                      ))}
                    </Select>
                  </Column>
                  <Column lg={8} md={4} sm={4}>
                    <Select
                      id="specimenConditionColumn"
                      labelText={intl.formatMessage({
                        id: "notebook.mntd.field.specimenCondition",
                        defaultMessage: "Specimen Condition",
                      })}
                      value={columnMapping.specimenConditionColumn}
                      onChange={(e) =>
                        handleMappingChange(
                          "specimenConditionColumn",
                          e.target.value,
                        )
                      }
                    >
                      <SelectItem value="" text="Select column..." />
                      {csvHeaders.map((header) => (
                        <SelectItem key={header} value={header} text={header} />
                      ))}
                    </Select>
                  </Column>
                  <Column lg={8} md={4} sm={4}>
                    <Select
                      id="remarksColumn"
                      labelText={intl.formatMessage({
                        id: "notebook.mntd.field.remarks",
                        defaultMessage: "Remarks",
                      })}
                      value={columnMapping.remarksColumn}
                      onChange={(e) =>
                        handleMappingChange("remarksColumn", e.target.value)
                      }
                    >
                      <SelectItem value="" text="Select column..." />
                      {csvHeaders.map((header) => (
                        <SelectItem key={header} value={header} text={header} />
                      ))}
                    </Select>
                  </Column>
                </Grid>
              </AccordionItem>
            </Accordion>

            {!isRequiredMappingComplete() && (
              <InlineNotification
                kind="warning"
                title={intl.formatMessage({
                  id: "notebook.mntd.manifest.mappingIncomplete",
                  defaultMessage:
                    "Please map all required fields before proceeding.",
                })}
                lowContrast
                hideCloseButton
              />
            )}

            {previewErrors.length > 0 && (
              <InlineNotification
                kind="error"
                title={intl.formatMessage({
                  id: "notebook.mntd.manifest.validationErrors",
                  defaultMessage: "Validation Errors",
                })}
                subtitle={
                  <ul className="error-list">
                    {previewErrors.map((error, idx) => (
                      <li key={idx}>
                        {error.rowNumber > 0 ? `Row ${error.rowNumber}: ` : ""}
                        {error.message}
                      </li>
                    ))}
                  </ul>
                }
                lowContrast
                hideCloseButton
              />
            )}
          </div>
        )}

        {/* Step 3: Preview */}
        {step === 3 && (
          <div className="import-step">
            <div className="step-header">
              <h5>
                <FormattedMessage
                  id="notebook.mntd.manifest.step3.title"
                  defaultMessage="Step 3: Preview Import"
                />
              </h5>
            </div>

            {isPreviewLoading ? (
              <Loading description="Loading preview..." />
            ) : (
              <>
                {previewData && (
                  <div className="preview-section">
                    {/* Summary Statistics */}
                    <div className="preview-stats">
                      <Tag type="blue">
                        <FormattedMessage
                          id="notebook.mntd.manifest.totalRows"
                          defaultMessage="Total Rows: {count}"
                          values={{ count: previewData.totalRows }}
                        />
                      </Tag>
                      <Tag type="green">
                        <FormattedMessage
                          id="notebook.mntd.manifest.validRows"
                          defaultMessage="Valid: {count}"
                          values={{ count: previewData.validRows }}
                        />
                      </Tag>
                      {previewData.totalRows - previewData.validRows > 0 && (
                        <Tag type="red">
                          <FormattedMessage
                            id="notebook.mntd.manifest.invalidRows"
                            defaultMessage="Invalid: {count}"
                            values={{
                              count:
                                previewData.totalRows - previewData.validRows,
                            }}
                          />
                        </Tag>
                      )}
                    </div>

                    {/* Validation Errors */}
                    {previewErrors.length > 0 && (
                      <div className="validation-errors-section">
                        <InlineNotification
                          kind="error"
                          title={intl.formatMessage({
                            id: "notebook.mntd.manifest.validationErrors",
                            defaultMessage: "Validation Errors",
                          })}
                          subtitle={intl.formatMessage(
                            {
                              id: "notebook.mntd.manifest.fixErrors",
                              defaultMessage:
                                "{count} error(s) found. Please fix the CSV and try again.",
                            },
                            { count: previewErrors.length },
                          )}
                          lowContrast
                          hideCloseButton
                        />
                        <div className="error-list">
                          {previewErrors.slice(0, 10).map((error, idx) => (
                            <div key={idx} className="error-item">
                              <strong>Row {error.rowNumber}:</strong>{" "}
                              {error.column} - {error.message}
                            </div>
                          ))}
                          {previewErrors.length > 10 && (
                            <div className="error-item">
                              ... and {previewErrors.length - 10} more errors
                            </div>
                          )}
                        </div>
                      </div>
                    )}

                    {/* Preview Table */}
                    {previewData.rows && previewData.rows.length > 0 && (
                      <div className="preview-table-section">
                        <h6>
                          <FormattedMessage
                            id="notebook.mntd.manifest.previewRows"
                            defaultMessage="Preview (first 10 rows)"
                          />
                        </h6>
                        <DataTable
                          rows={previewData.rows
                            .slice(0, 10)
                            .map((row, idx) => ({
                              id: String(idx),
                              rowNumber: row.rowNumber,
                              sampleIdTag: row.sampleIdTag || "-",
                              sampleType: row.sampleType || "-",
                              projectName: row.projectName || "-",
                              sourceLocation: row.sampleSourceLocation || "-",
                              broughtBy: row.broughtBy || "-",
                            }))}
                          headers={[
                            { key: "rowNumber", header: "Row #" },
                            { key: "sampleIdTag", header: "Sample ID/Tag" },
                            { key: "sampleType", header: "Sample Type" },
                            { key: "projectName", header: "Project" },
                            { key: "sourceLocation", header: "Source" },
                            { key: "broughtBy", header: "Brought By" },
                          ]}
                        >
                          {({
                            rows,
                            headers,
                            getTableProps,
                            getHeaderProps,
                            getRowProps,
                          }) => (
                            <Table {...getTableProps()} size="sm">
                              <TableHead>
                                <TableRow>
                                  {headers.map((header) => (
                                    <TableHeader
                                      key={header.key}
                                      {...getHeaderProps({ header })}
                                    >
                                      {header.header}
                                    </TableHeader>
                                  ))}
                                </TableRow>
                              </TableHead>
                              <TableBody>
                                {rows.map((row) => (
                                  <TableRow
                                    key={row.id}
                                    {...getRowProps({ row })}
                                  >
                                    {row.cells.map((cell) => (
                                      <TableCell key={cell.id}>
                                        {cell.value}
                                      </TableCell>
                                    ))}
                                  </TableRow>
                                ))}
                              </TableBody>
                            </Table>
                          )}
                        </DataTable>
                      </div>
                    )}
                  </div>
                )}
              </>
            )}

            {isImporting && <Loading description="Importing samples..." />}
          </div>
        )}

        {/* Step 4: Success */}
        {step === 4 && (
          <div className="import-step">
            <InlineNotification
              kind="success"
              title={intl.formatMessage({
                id: "notebook.mntd.manifest.importSuccess",
                defaultMessage: "Import Successful",
              })}
              subtitle={intl.formatMessage({
                id: "notebook.mntd.manifest.importSuccessMessage",
                defaultMessage:
                  "Samples have been imported successfully. You can now view them in the sample list.",
              })}
              lowContrast
              hideCloseButton
            />
          </div>
        )}
      </div>
    </Modal>
  );
}

export default MNTDManifestImportModal;
