name: Publish STAGING images to GHCR

on:
  push:
    branches: [demo/ethiopia-main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish-staging:
    uses: ./.github/workflows/publish-ghcr.yml
    with:
      tag: staging
      include_sha_tag: true
      include_latest_tag: false
      include_day_tag: true
